### ISSUE TITLE
Multi-thread support for aggregator

### ISSUE THREAD

**Issue by Neway6655** [grobian/carbon-c-relay#60] opened 2015-04-10 03:35 UTC
Is it possible to support multi-thread for aggregator?

I have a scenario which the performance is seems blocking at the aggregation, as I have millions of metrics received every min, and all those metrics are needed to be aggregated, the configuration file looks like this:
```
cluster local_carbon
  forward
    192.168.0.138:2013
  ;
match ^metrics.all.*
  send to local_carbon
  stop
  ;
aggregate
        metrics.*.api.ac\.([^.]+)\.([^.]+)\.([^.]+)\.([^.]+)\.([^.]+)\.count
    every 10 seconds
    expire after 50 seconds
    compute sum write to
        metrics.all.api.ac.\1.\2.\3.\4.\5.count
    compute sum write to
        metrics.all.api.ac.\1.\2.all.\4.\5.count
    compute sum write to
        metrics.all.api.ac.\1.\2.\3.all.\5.count
    compute sum write to
        metrics.all.api.ac.\1.\2.all.all.\5.count
    ;
```
and I have glanced the code(aggregator.c) a little bit, maybe it can be changed to bind one thread for every aggregator, instead of all aggregators?

**Comment by grobian** [comment] 2015-04-10 19:52
Wow, that's unexpected! I've never got the aggregator on its knees :)  Guess we really don't do much aggregating.

**Comment by grobian** [comment] 2015-04-10 20:16
If your real config really is like you posted above, the problem is not easily solved by multiple threads, for it is cumbersome to lock on the individual metrics.
From a different angle, what makes you think the aggregator thread is actually not coping to keep up with the expiry work?

**Comment by Neway6655** [comment] 2015-04-11 06:54
I have wrote a simulator to batch send 600,000 metrics every 10s, and I found the CPU of carbon-c-relay goes  up to around 120% in 3 seconds, and after a while, I found the metrics were delayed a lot(several mins) to be sent, so i was wondering that there may be some bottleneck, i guess it may be caused by the  aggregation thread locking some resources, which blocks the metrics receiver. 

The metrics data in my case was a little bit special, the 7th field ('\3')'s dimension was a very big, e.g. 4000, so even after the aggregation, the total metrics generated were still very huge, which may cause the aggregator too busy? because same issue was found when using carbon-aggregator (and that's the reason why i want to give carbon-c-relay a try).

**Comment by grobian** [comment] 2015-04-11 07:17
Yes, I assumed you'd have a huge expansion.  Reason why this is non-trivial to multi-thread is that it is a single aggregation rule, so the sharding of the workload is non-trivial (and would require locks).  I'm trying to think of a way in which to make the expiry work being done by the main worker threads instead of a single one.

Is your simulator by any chance available somewhere so I can use it instead files + nc?

**Comment by Neway6655** [comment] 2015-04-13 02:58
Yes, I have uploaded my simulator code into gist: https://gist.github.com/Neway6655/1f7657790c2869199c30

and you can update the 7th field's dimension by changing MAX_APP's value.

**Comment by EvanKuhn** [comment] 2015-04-13 17:16
Just noting that I've run into basically the same problem.  Sending about 120,000 metrics every 10 seconds from multiple hosts to a single carbon-c-relay.  CPU on the relay was at ~130%, and metrics starting getting delayed. Looked like they were getting backed up in the socket send/receive queues.

I also tried closing and reopening a new socket every 10 seconds.  Metrics made it to the carbon-c-relay host more quickly, but just ended up waiting in the various socket receive queues, as seen via netstat.

So, looks like the aggregator was not able to keep up.  

For comparison, CPU usage of the relay with aggregation on is a constant 130%, and off is anywhere from 0-30% (it spikes when metrics arrive).

Also, my metrics paths are not extremely long, about 100 chars total.

My aggregation rules look like:

```
aggregate
        ^adserv\.([^.]+)\.([^.]+)\.host\.([^.]+)\.(.+)$
    every 10 seconds
    expire after 10 seconds
    compute sum write to
        adserv.\1.\2.all.sum.\4
    compute average write to
        adserv.\1.\2.all.avg.\4
    ;
```

Looking forward to seeing if you guys find anything.

**Comment by grobian** [comment] 2015-04-13 18:26
I can easily reproduce, currently exporing the problem space ...

**Comment by Neway6655** [comment] 2015-04-14 04:24
Just did another test, I changed expire seconds to 600s, then I found the simulator was blocked once the metrics were sent to carbon-c-relay, we didn't need to wait for 600s, so I guess the issue might not caused by expiry work, 

so I checked the code(aggregator.c) again, I guess it might be caused by this lock: https://github.com/grobian/carbon-c-relay/blob/master/aggregator.c#L158, 
because compute->invocations will be thousands, and I have some concerns about the search efficiency, as there are 600,000 metrics coming in every 10s , which means there will be 600,000 * 4000(4000 APPs, ) loops in 10s.

**Comment by grobian** [comment] 2015-04-14 08:05
Good digging, I arrived at the same conclusion yesterday.  This happened because originally the aggregator didn't do expansion, and a static config was optimised (the optimiser is still in place) to make sure we could deal with this.  This is good in a way, because it makes it easier for me to fix.  The workers simply take too long to find the right invocation, but a hash or the previously mentioned optimisation tree could help here.  I guess in both your cases a single stream is sent to the aggregator.  In my environment here, multiple streams are maintained, therefore more workers are doing work iso just one.

**Comment by Neway6655** [comment] 2015-04-20 10:37
hi grobian, your commit: https://github.com/grobian/carbon-c-relay/commit/484d4680efa4348fae328c96c2965ec950a72c49 was a nice solution, but unfortunately, I tried it and seems my issue was still existed, and I have no idea where the problem is now...  Did this commit worked in your env?

**Comment by grobian** [comment] 2015-04-20 11:21
No it didn't :( I suspect it did improve somewhat, but not as much as I hoped for.  I'm affraid I made a wrong decision in the past somewhere, because I cannot parallelise this work in the current way of doing things (I'm forcing the worker to block on the aggregation work). I might give it a try to make the aggregation bit faster before I change the relay to schedule the aggregation work in a different run of the workers.

**Comment by EvanKuhn** [comment] 2015-04-23 19:30
As a secondary solution, would it be worthwhile to create a new hashing algorithm similar to carbon's `aggregated-consistent-hashing`?  This would allow us to set up the following on a single host:

1) A single 'frontend' carbon-c-relay relays all metrics to a set of 'backend' carbon-c-relay processes.
2) The 'backend' carbon-c-relay processes are responsible for for aggregation.

This would allow us to scale aggregation by adding more backend carbon-c-relays.

To be honest I don't really like this solution; I'd prefer to have a single multi-threaded process handle all the work, rather than use carbon's multi-process style architecture.  But if it's easy to add this new aggregated-consistent-hashing algorithm, then it'd provide a backup solution until better multi-threaded aggregation support can be added.  It'd also allow us to scale to multiple boxes if a single box couldn't handle all relay + aggregation work (even with ideally-threaded code).

**Comment by grobian** [comment] 2015-04-23 19:47
I don't quite get it.  We do consistent hashing already, not sure what "aggregated-consistent-hashing" would do.

The problem of the relay with the current workload is that it reads a block from a client one thread at a time, and that thread gets too busy figuring out what to aggregate.  It feels more sensical to me when other worker threads can help out in this case.  I think we can do so by using a queue in front of the aggregator.  I haven't gotten around to doing so, but I will, for this clearly is faulty behaviour of the relay.

**Comment by EvanKuhn** [comment] 2015-04-23 23:45
@grobian Totally agree w you that using other worker threads is a better solution.  If you can get that working, then great.

Carbon's `aggregated-consistent-hashing` is slightly different than normal consistent hashing in that it takes aggregation rules into account, so that all metrics that should be aggregated together are sent to the same aggregator (see https://github.com/graphite-project/carbon/blob/master/conf/carbon.conf.example). I only suggested that as a backup solution, to allow for running multiple carbon-c-relays to function as aggregators.  If all relay + aggregation can be done by a single process, then that's much simpler (though I suppose one could argue that if you want carbon-c-relay to be able to scale horizontally, you might want aggregated-consistent-hashing).

Anyway, I'll wait for the multi-threaded solution.  Thanks.

**Comment by grobian** [comment] 2015-04-27 18:25
I see now where the `aggregated-consistent-hashing` comes in.  Obvious problem with it is that the router needs to be aware of the aggregation rules, and potentially just has to duplicate traffic (at a very expensive cost).  Horizontally scalable aggregation would be a topic for the future, but involve a distributed aggregation approach (map-reduce if you like), which for now I'd like to avoid :)

**Comment by grobian** [comment] 2015-04-30 11:39
This takes so long because there is an important feedback loop inside the relay that cannot be broken, and prevents per-connection parallelism.  Hence, first plan is to make sure the roundtrip time per metric is O(1) complexity.  That should bring us very close to what would happen if we'd split the traffic first into multiple streams (to gain parallelism).  Tests I did where I ran the traffic through the relay without aggregation (simple matching) showed that a sufficient performance was met to clear the input stream without being CPU bound.

**Comment by grobian** [comment] 2015-05-01 08:23
With the stress tester from Neway6655 I can't get my MacMini to be impressed any more.  It nicely eats the incoming stream without hitting cpu limit.  Could you give it a spin to verify I didn't do something horribly wrong?

**Comment by Neway6655** [comment] 2015-05-05 09:50
Wow, It nicely fixed my issue here, I did a verification on my environment, and all went well. Thanks a lot! You must be the most diligent guy working on the Labor Day :)

**Comment by grobian** [comment] 2015-05-05 10:44
Haha, we don't celebrate Labor Day, but we do celebrate Liberation Day (today) ;)

**Closed by grobian** 2015-05-05 10:44 UTC
