### ISSUE TITLE
carbon-c-relay[11578]: segfault at 7f6c224ab000 ip 0000003a7fc89d1b sp 00007f6c0f5fdc58 error 4 in libc-2.12.so[3a7fc00000+18a000]

### ISSUE THREAD

**Issue by piotr1212** [grobian/carbon-c-relay#71] opened 2015-05-18 06:54 UTC
I've seen this twice the past few months. We run carbon-c-relay on about 10 hosts so it doesn't happen that often. This is on RHEL 6.6 with 0.39. Will try to hook a debugger up.

**Comment by grobian** [comment] 2015-05-18 09:00
that would be awesome! I've done many attempts, but never ran into a crash

**Comment by piotr1212** [comment] 2015-05-18 09:06
I can't reproduce and the systems appear to have core dumps disabled.... I will enable the core dumps and then wait for it to occur again...

**Comment by grobian** [comment] 2015-05-24 19:31
this is probably a duplicate of issue #62

**Closed by grobian** 2015-05-24 19:31 UTC
