### ISSUE TITLE
Percent symbol (%) segfaulting v3.0

### ISSUE THREAD

**Issue by G-regL** [grobian/carbon-c-relay#263] opened 2017-04-24 19:21 UTC
Hi there,

I've just tried to use version 3.0, but it's segfaulting.

```
[2017-04-24 14:52:34] starting carbon-c-relay v3.0 (2017-04-24), pid=5304
configuration:
    relay hostname = servername-test
    listen port = 2003
    workers = 4
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    listen backlog = 32
    server connection IO timeout = 600ms
    extra allowed characters = -_:#%$|
    configuration = /etc/carbon-c-relay/relay.conf

/etc/carbon-c-relay/relay.rewrite.d/02-windows_general.conf:7:31: syntax error, unexpected string, expecting 'into'
rewrite ^(.+)\.win_(.+)\.(.+)\.%_(.+)
                               ^
Segmentation fault
```

The config file in question looks like this:
```
rewrite ^(.+)\.win_cpu\._Total\.(.+)
  into \1.win_cpu.\2
;
rewrite ^(.+)\.win_disk\.(.+)\.Avg\._Disk_sec[\/_-](Read|Write)
  into \1.win_disk.\2.Avg_Disk_sec_\3
;
rewrite ^(.+)\.win_([^.]+)\.(.+)\.\%_(.+)
  into \1.win_\2.\3.Percent_\4
;
```

If I comment out the line with the `%`, it segfaults on the next occurrence of it.

It works fine in 2.6, as well as 2.1.

**Comment by grobian** [comment] 2017-04-24 19:24
Any chance you could get me a backtrace for the crash?  I need to apply a fix for this to work like it did for 2.6, or you can quote the expressions like so:
```
rewrite "^(.+)\.win_(.+)\.(.+)\.%_(.+)"
  into \1.win_\2.\3.Percent_\4
;
```

**Comment by G-regL** [comment] 2017-04-24 19:25
I'd be happy to get you a backtrace, but how does one go about that?

I also didn't realize I could quote the expressions, but I'll try that too.

**Comment by G-regL** [comment] 2017-04-24 19:28
Oh, and it's also segfaulting on `<`'s in expressions too, but I can say that quoting the expressions seems to work.

Let me know if you still want a backtrace.

**Comment by grobian** [comment] 2017-04-24 19:32
You'll have to compile the relay yourself for that.  If you're not used to that, it's ok.  I can't reproduce the crash, which is ugly and seems caused by the parse error.
The quoting is new in v3.0 since the parser changed considerably in that version (hence the problem with the characters).

**Comment by G-regL** [comment] 2017-04-25 20:31
I see you committed a change which seems to fix it, but did you still want me to compile the relay to generate a backtrace?

**Comment by grobian** [comment] 2017-04-26 08:36
If not to much hassle to you, compile v3.0 from sources: `make CFLAGS="-O0 -g -pipe"` then run it using `gdb --args ./relay -f <your config>`.  That should generate segfault, `bt` on gdb's prompt should give some indication.

**Comment by G-regL** [comment] 2017-04-27 11:50
Alright, I've managed to run the relay using `gdb`, and here's the output. Hopefully it makes more sense to you than me. :smile: 

```
# gdb --args ./relay -f /etc/carbon-c-relay/relay.conf -c '-_:#%$|' -t -H server-test
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/carbon-c-relay_3.0_debug/relay...done.
(gdb) run
Starting program: /opt/carbon-c-relay_3.0_debug/./relay -f /etc/carbon-c-relay/relay.conf -c -_:\#%\$\| -t -H server-test
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[2017-04-27 07:47:34] starting carbon-c-relay v3.0 (2017-04-27), pid=3026
configuration:
    relay hostname = server-test
    listen port = 2003
    workers = 4
    send batch size = 2500
    server queue size = 25000
    server max stalls = 4
    listen backlog = 32
    server connection IO timeout = 600ms
    extra allowed characters = -_:#%$|
    configuration = /etc/carbon-c-relay/relay.conf

/etc/carbon-c-relay/relay.rewrite.d/02-windows_general.conf:7:25: syntax error, unexpected string, expecting 'into'
rewrite ^(.+)\.win_(.+)\.%_(.+)
                         ^

Program received signal SIGSEGV, Segmentation fault.
0x0000000000414251 in router_validate_expression (rtr=0x62b0d0, retr=0x7fffffff7928, pat=0x66fa49 "^(.*\\.sqlserver)\\.(.*)_\\|_(.*)_\\|_Deprecated_Features\\.([^.]*)\\.Performance_counters", subst=1 '\001') at router.c:500
500                     r->next = NULL;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64
(gdb) bt
#0  0x0000000000414251 in router_validate_expression (rtr=0x62b0d0, retr=0x7fffffff7928, pat=0x66fa49 "^(.*\\.sqlserver)\\.(.*)_\\|_(.*)_\\|_Deprecated_Features\\.([^.]*)\\.Performance_counters", subst=1 '\001') at router.c:500
#1  0x000000000040adce in router_yyparse (yyscanner=0x62b0d0, rtr=0x62b0d0, ralloc=0x62e3a0, palloc=0x62e370) at conffile.y:492
#2  0x0000000000415f3f in router_readconfig (orig=0x62b0d0, path=0x62f8d7 "/etc/carbon-c-relay/relay.rewrite.d/02-windows_sqlserver.conf", queuesize=0, batchsize=0, maxstalls=0, iotimeout=0, sockbufsize=0) at router.c:1121
#3  0x000000000040b939 in router_yyparse (yyscanner=0x62b190, rtr=0x62b0d0, ralloc=0x62b160, palloc=0x62f180) at conffile.y:745
#4  0x0000000000415f3f in router_readconfig (orig=0x62b0d0, path=0x7fffffffe7db "/etc/carbon-c-relay/relay.conf", queuesize=25000, batchsize=2500, maxstalls=4, iotimeout=600, sockbufsize=0) at router.c:1121
#5  0x0000000000403f85 in main (argc=8, argv=0x7fffffffe558) at relay.c:714
```

**Comment by grobian** [comment] 2017-04-27 18:33
Thanks! Found the issue, and can reproduce, will fix it!

**Comment by grobian** [comment] 2017-04-29 09:54
I've added both the fix for the crash, as well as suppor for the extra chars in the expressions.  Closing this bug, please reopen if issues persist.

**Closed by grobian** 2017-04-29 09:54 UTC
Labels: bug
