### ISSUE TITLE
Incoming aggregated metrics are not de-duplicated

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [grobian/carbon-c-relay#114] opened 2015-10-27 09:59 UTC
Not sure whether this is a bug or an observable feature.  It seems that, given an aggregation configured with:
```
    every 300 seconds
    expire after 900 seconds
```
If, for whatever reason, the same metric is sent to the relay more frequently than every 300 seconds (eg: three times every 300 seconds), the output of the aggregation does not discard any duplicated data.

Of course, fixing the collectd script interval to match carbon-c-relay fixes this observed behaviour.

**Comment by grobian** [comment] 2015-10-27 16:40
I'm not sure I understand you well here.  The purpose of the aggregator is to fold multiple metrics into one, how should it de-duplicate metrics exactly?

**Comment by iain-buclaw-sociomantic** [comment] 2015-10-27 18:38
If the following metric line is received by the relay
```
foo.bar.value 12.34 1234567890
```
And then received again for a second time before the ``every XX seconds`` ticks over, then the aggregator will return:
```
foo.bar.value
  count: 2
  sum: 24.68
  max: 12.34
  min: 12.34
```
Where in fact it was expected was ``sum: 12.34``.

**Comment by grobian** [comment] 2015-10-28 14:46
Oh, that's what you mean.  That's very hard to do at this stage, and will be expensive as well.

I guess this is more of a feature request then ;)

**Comment by bzed** [comment] 2015-10-29 11:14
You could track the last timestamp of a metric and only accept more recent timestamps.

**Comment by grobian** [comment] 2015-10-29 12:04
Sure could, but the aggregator is made for aggregating buckets, so e.g. 5 machines producing a metric and building a sum.  For whatever reason the timestamps could be out of order, and there is no valid reason why those metrics should be discarded IMO.  That's what the expire is also designed for: to cater with wildly out of order arriving metrics (e.g. after an interruption in the stack somewhere)

**Comment by iain-buclaw-sociomantic** [comment] 2015-10-29 20:06
> That's what the expire is also designed for: to cater with wildly out of order arriving metrics (e.g. after an interruption in the stack somewhere)

My case only came up because the metric timestamps are taken from reading the last line of a log file.  And then it could happen that the same log line is sent multiple times if nothing new was written.

**Comment by grobian** [comment] 2015-11-05 07:38
I'm going to close this ticket, since I'm not sure how to fix this without expensive storage and computation overhead.  It is not something the aggregator was designed for, nor easy to adapt for.

**Closed by grobian** 2015-11-05 07:38 UTC

**Comment by iain-buclaw-sociomantic** [comment] 2015-11-05 09:27
That's fine.  I've since fixed the buggy collectd scripts anyway.
