### ISSUE TITLE
Relay Statistics

### ISSUE THREAD

**Issue by gdavis33** [grobian/carbon-c-relay#38] opened 2015-01-06 23:05 UTC
I know the relay can send it's own statistics into the stats stream because I'm sure I saw them during my testing. Now however, they no longer show up. I've tried starting with debug and they do print to stdout.

```
# Define the local carbon cache cluster
cluster local_cache
    any_of
        127.0.0.1:2003
        127.0.0.1:2103
        127.0.0.1:2203
        127.0.0.1:2303
    ;

# Define the AWS storage cluster
cluster aws_store
    carbon_ch
        <ip>:2113
        <ip>:2113
        <ip>:2113
        <ip>:2113
    ;

# Send everything to local
match *
    send to local_cache
    ;

# Send everything to AWS
match *
    send to aws_store
    ;
```

**Comment by grobian** [comment] 2015-01-07 06:26
they should be under carbon.relays.<hostname>

**Comment by Civil** [comment] 2015-01-07 09:58
I don't know if it's expected behavior or not, but if you start relay with "submission mode" enabled, it won't send any statistics.

**Comment by gdavis33** [comment] 2015-01-07 16:19
Hmm, is that a bug or by design? it seems like statistics and "-s  submission mode: write info about errors to stdout" are both desirable.

**Comment by chjohnst** [comment] 2015-01-08 13:01
I have the same issue, I used to get stats then I modified my syntax and
after awhile I noticed I wasn't receiving them anymore.

**Comment by grobian** [comment] 2015-01-08 13:35
The purpose of -s (submission mode) is not to pollute the metrics stream with the relay its own metrics/statistics.  This is because the relay is only used to "submit" to an upstream relay.  If you want statistics, don't use -s.  You don't need the info about errors bit, for the relay sends that info as metric when you don't use submission mode.  (The only thing it does it tell you when it drops an awful amount of metrics.)

I believe this bug is about not getting statistics when running in submission mode, therefore I close this bug, as that is intended behaviour.  Please reopen if the issue is different.

**Closed by grobian** 2015-01-08 13:35 UTC
